- hosts: webserver
  become: yes
  tasks:
   - name: install httpd on webservers
     action: yum name=httpd state=installed
     notify: restart httpd
  handlers:
   - name: restarted httpd
     action: service name=httpd status=restarted